### ISSUE TITLE
How might we raise awareness of the values we want to see underlying openness? [ Workshop Challenge ]

### ISSUE THREAD

**Issue by thessaly** [sparcopen/doathon#25]
_Confused? New to Github? Visit the [GitHub help page on our site for more information](http://doathon.opencon2017.org/)!_

[//]: # "=======================
Even if you know Github well, we suggest you read this. Anything between these lines you can leave or delete, as they won't display anyway when you post (you can check this via Preview changes). They're here to help you complete issues quickly and in a way that will help other participants. If you're posting a new project, or challenge. We suggest you fill out the Google Forms first.
============================"

## At a glance

[//]: # "=======================
Please paste the metadata you received after submitting your project or challenge in your Google Form exactly as we sent it to you. You can delete what's there now, it's just there
============================"

* **Submission Name:** _How might we raise awareness of the values we want to see underlying openness?_
* **Contact Lead:** _jarancio@fund-cenit.org.ar_
* **Region**: _#LatinAmerica_and_Caribbean_
* **Issue Area:** _#OpenAccess, #OpenData, #OpenEducation, #OpenResearch_
* **Issue Type:** _#Challenge_

## Description
[//]: # "=======================
Insert a paragraph providing more context for your project or challenge focuses on. For project leads, this is a good place to give some broader context about your project—beyond the scope of the do-a-thon. If you're posting a challenge, this is a good chance to say how the problem arise or why it feels relevant to you.
============================"
OpenCon this year will include workshops focused on advancing regional-specific issues in Open Research and Open Education. In one of these workshops we’re proposing and going to be working through _How might we raise awareness of the values we want to see underlying openness?_

Although there's an important and long-term tradition of Open Access, Data, Research and Education initiatives in Latin America, do we all share the same values and principles underlying openness? How do we face the 'Open washing' in the region -e.g. Commercial publishers that start 'selling' openness-? Can we work on a way of making these values more visible, strong and context appropriate?

We’re interested in this because we think there's a risk of losing openness due to the recent 'open washing' discourse in the region. 

During the workshop (as well as before—and after!) we invite anyone to help tackle this challenge. You don’t need to be part of the workshop — or conference to share your thoughts and ideas! We’ll keep this issue up to date with anything we do or learn.

##  How can others contribute?
[//]: # "======================= 
Please say what the best way to contribute to the project or challenge is, sometimes that will just be 'lets discuss here' or 'Ive started a Google doc'. 
If you are a challenge lead, give some context on what design thinking tools you will be using, and how other folks can update their ideas onto the thread. 
If you are a project lead, and you already have clear ways people can contribute it might be worth linking to them here.
Language: If your project is regionally based in a non-English-speaking region, clarify here what language you and contributors will primarily be communicating in. 
If you're leading a project or challenge participating remotely: Use this space to let people know that this is a remote project and that you are not 'in the room' in Berlin. Let other participants know what the best way to get in touch with you, where the work will happen, and where any updates or outputs will go. 
If you are at the in-person meeting in Berlin: Be as inclusive as possible to those outside the room.  Use this space to give clear instructions to those participating in the do-a-thon remotely on how they can keep up to date and contribute. ============================"
Let's start the discussion here! 

Anyone can contribute to these efforts. The place to start in helping us more deeply understand the challenge from more angles. We invite you to jump in the comments section and share any thoughts. Before the workshop, we’ll use that to help make sure our theme has the right emphasis and help plan the workshop.

For those not in the room, subscribe to this issue. We’ll post our outputs and notes here immediately after every session! 

If you have an idea or comment to share that isn’t in the [problem refinement exercise](https://docs.google.com/document/d/1uOP9JgQsSLOH7vC7TNfiuSwjb6wkeksbX5fX9Kz8EM0/edit?usp=sharing) and that you think won’t be covered in the workshop, we’d love to hear from you in the Github comments below. 

[//]: # "=======================
You're ready to post!!! After posting your issue, the real work begins. Next, you might want to:
   Tweet a link to this issue with #opencon so others can join in
   Make another issue to involve people in your work - remember to use your metadata
   Come back from time to time and update the community on your project.
You'll get an email update whenever someone interacts with your issue.
============================"

_This post is part of the OpenCon 2017 Do-A-Thon. Not sure what's going on? [Head here](http://doathon.opencon2017.org/)._

**Comment by lorrainechu3n** [comment]
## Empathy Maps (Session 1 Outputs) 

<img src="https://photos-4.dropbox.com/t/2/AACDkEEWBoGAZRldCaQyqe7cT6dsLb2SkV36SaRZjTN6jA/12/308295712/jpeg/32x32/3/1510549200/0/2/537A1776.JPG/EICDwbwGGF8gBygH/jFgWRdFK_FvL_bHl4ktwuDHbjov0iYJj-Ei83p1H2r0%2CP16Re_vcog3mqfwmobIBAu47EfBjl6PNg5WH-Wy6qGE?dl=0&size=2048x1536&size_mode=3">
<img src="https://photos-2.dropbox.com/t/2/AADjX2jDt2C7s4gaGz3Ay1DlPp14wpfHRgbKOqPSJAN13g/12/308295712/jpeg/32x32/3/1510549200/0/2/537A1777.JPG/EICDwbwGGF8gBygH/lTNoskZj7CRuHRgY3NuqF8c4frd5VBNdIVkDEC0wujA%2Cg93BzxifY-fJjSnfIRP5pJCfY1DQ8Upu1fokgdHr43s?dl=0&size=2048x1536&size_mode=3">
<img src="https://photos-6.dropbox.com/t/2/AACG1Z2fYlIwBZKjv5ieWwy6r7tKSW6t0VrBA87gWSnF3Q/12/308295712/jpeg/32x32/3/1510549200/0/2/537A1778.JPG/EICDwbwGGF8gBygH/v1Epku2-UCnSa0ejMofD_RzirFYQ6plhk7pFwH2u5zY%2CPdyBzxMEbZcH7hQJVv__a3yKHjUkw2jvd0xnQYGxOkg?dl=0&size=2048x1536&size_mode=3">
<img src="https://photos-6.dropbox.com/t/2/AACAVxKmXbGk5YmvbuH_CgfNwE2S0viVd7NiKSD2NejIAA/12/308295712/jpeg/32x32/3/1510549200/0/2/537A1779.JPG/EICDwbwGGF8gBygH/hKD3WEGfh5R7i-YvfYy7O6WuSbow4ks-IiLeOLAqENM%2ClmUikHQzBQ9szLIbvU2eJp2PXcmfIWNc9PPItulo2pQ?dl=0&size=2048x1536&size_mode=3">
<img src="https://photos-6.dropbox.com/t/2/AAAeyGACOkNX1oxpvIDv6JBsL8Wj7TknKtUQ9rbv8VOYPg/12/308295712/jpeg/32x32/3/1510549200/0/2/537A1849.JPG/EICDwbwGGF8gBygH/n_cvQC6QOWyAzAG200Rhb3nJZE9q5SGWOkJZsKk7S6s%2CHOAKC3VwrHHlJ6C1hHZdQST1BejBi0xl6q_XrYW7aSw?dl=0&size=2048x1536&size_mode=3">

**Comment by lorrainechu3n** [comment]
## Empathy Maps --> Problem Statements (Session 2 Outputs)
<img src="https://photos-2.dropbox.com/t/2/AACtY-ETz3I49RKKVerrCt0A4JDVPSeTww6cAE2axF82iw/12/308295712/jpeg/32x32/3/1510549200/0/2/537A1850.JPG/EICDwbwGGF8gBygH/MEuzWwNfguNvJORZ4KGLcFmEGKU4hIP9MpYi6xIYTxI%2CgmTdp1_YdKfSMltK-wazJ4yv8uurY1HByPyDI_Zulcg?dl=0&size=2048x1536&size_mode=3">
<img src="https://photos-1.dropbox.com/t/2/AADkiUZ79odaGubdORAa17H5xPzYRLgf67_U987Gw-AinQ/12/308295712/jpeg/32x32/3/1510549200/0/2/537A1851.JPG/EICDwbwGGF8gBygH/__4I_6Wmw0N4nG4OGNUIUyipxQ7y6seRWFHcinx7n6E%2C1CM2d6Bj5fMZDPtoJSKAqH_j1S3k-v9I1ZwPMl5fQUo?dl=0&size=2048x1536&size_mode=3">
<img src="https://photos-2.dropbox.com/t/2/AACtY-ETz3I49RKKVerrCt0A4JDVPSeTww6cAE2axF82iw/12/308295712/jpeg/32x32/3/1510549200/0/2/537A1850.JPG/EICDwbwGGF8gBygH/MEuzWwNfguNvJORZ4KGLcFmEGKU4hIP9MpYi6xIYTxI%2CgmTdp1_YdKfSMltK-wazJ4yv8uurY1HByPyDI_Zulcg?dl=0&size=2048x1536&size_mode=3">
<img src="https://photos-1.dropbox.com/t/2/AADkiUZ79odaGubdORAa17H5xPzYRLgf67_U987Gw-AinQ/12/308295712/jpeg/32x32/3/1510549200/0/2/537A1851.JPG/EICDwbwGGF8gBygH/__4I_6Wmw0N4nG4OGNUIUyipxQ7y6seRWFHcinx7n6E%2C1CM2d6Bj5fMZDPtoJSKAqH_j1S3k-v9I1ZwPMl5fQUo?dl=0&size=2048x1536&size_mode=3">
<img src="https://photos-3.dropbox.com/t/2/AAAU1LgA-ybmJzhQCDjv97Gh5ALUQ8dc4H1q6XaZ5p0y9A/12/308295712/jpeg/32x32/3/1510549200/0/2/537A1852.JPG/EICDwbwGGF8gBygH/-mqOfkyLofTbo0KzAru-YWQtbe3gA_Z_XsFvC14Yk8Q%2C_Wn6YWZXff99LnTjFEgeqDUYQYGDN-mI8uK-RXMu9Bk?dl=0&size=2048x1536&size_mode=3">

**Comment by thessaly** [comment]
I'm closing this issue for 2018 as it was part of a Workshop last year.
