### ISSUE TITLE
How might we go beyond quantitative data, beyond journals, beyond hard sciences?

### ISSUE THREAD

**Issue by HanjoHamann** [sparcopen/doathon#50]
Submission name: How might we go beyond quantitative data, beyond journals, beyond hard sciences?

Contact lead: hamann@coll.mpg.de

Issue area: #OpenAccess, #OpenData

Region: #Europe

Issue Type: #Challenge

## Description:
As of yet, most Open Science discussion has been exclusively about hard sciences that publish primarily quantitative data in journals with an online (albeit paywalled) interface. Many academic disciplines do not fall into this category, so how do we extend the movement to humanities or other disciplines that publish primarily books and monographs? How do we treat publishers that actually provide substantial surplus to authors, rather than just siphoning off corporate profit? How do we deal with qualitative data that cannot easily be published without revealing personal information about study subjects, ect.? All of these questions have barely been discussed and need to be addressed urgently in order to avoid a new split between scientific disciplines along the lines of "hard" and "soft" (or "modern" and "antiquated") scientific inquiry. We will jointly address these and other related challenges.

**Comment by HanjoHamann** [comment]
The OHSS (Open Humanities and Social Sciences) group is starting in the Harnack House's RUSKA room now.

**Comment by RaoOfPhysics** [comment]
What was the outcome of this challenge? Was it abandoned?

**Comment by HanjoHamann** [comment]
Our work on that got merged into Zoe's Git. I would have deleted the issue, but GitHub being the beautiful software that it is: Mission impossible ;)

**Comment by RaoOfPhysics** [comment]
Sounds good, thanks for following up. :)
